INSERT INTO assignments (name, title, description, type, duration) VALUES ('Homework 1', 'The Pythagorean Theorem', 'Ten exercise problems to orient students with solving for the length of the hypotenuse', 'homework', '60');
INSERT INTO assignments (name, title, description, type, duration) VALUES ('Homework 2', 'The Cross Product', 'Ten exercise problems to orient students with performing the cross product operation', 'homework', '60');
INSERT INTO assignments (name, title, description, type, duration) VALUES ('Lab 1', 'Ionic and Covalent Bonds', 'A lab to introduce students to types of bonding.', 'lab', 60);
INSERT INTO tags (name) VALUES ('homework');
INSERT INTO tags (name) VALUES ('math');
INSERT INTO tags (name) VALUES ('cross product');
INSERT INTO tags (name) VALUES ('pythagorean theorem');
INSERT INTO tags (name) VALUES ('lab');
INSERT INTO tags (name) VALUES ('project');
INSERT INTO tags (name) VALUES ('practice test');
INSERT INTO tags (name) VALUES ('chemistry');
INSERT INTO assignmentsTags VALUES (1, 1);
INSERT INTO assignmentsTags VALUES (1, 2);
INSErT INTO assignmentsTags VALUES (1, 4);
INSERT INTO assignmentsTags VALUES (2, 1);
INSErT INTO assignmentsTags VALUES (2, 2);
INSERT INTO assignmentsTags VALUES (2, 3);
INSERT INTO assignmentsTags VALUES (3, 5);
INSERT INTO assignmentsTags VALUES (3, 8);
